### ISSUE TITLE
Create basic gulpfile to load tasks and confs by each environment

### ISSUE THREAD

**Issue by garusis** [garusis/gulp-multienv-approach#1]
- [ ] Make loadFile function documentation (#5).
- [ ] Make loadJsonFile function documentation (#6).
- [ ] Make loadConfFile function documentation (#8).
- [ ] Make loadTasks function documentation (#7).
- [ ] Make loadConfig function documentation (#9).
